fix GIT_UP with a workaround (leave a TODO) and set a working revision
33308c1e14f0eaed9d204d00aff9c0193608dde6 don't work ROS because of  ../../lib/libpcl_io.so.1.7.0: undefined reference to `ros::TimeBase<ros::Time, ros::Duration>::fromNSec(unsigned long long)'