pcl_conversions: Fix compile errors caused by rosidl_buffer introduction
Compiling pcl_ros package in rolling results in errors like this:

    In file included from
    /build/perception_pcl-release-release-rolling-pcl_ros-2.8.0-1/tools/combined_pointcloud_to_pcd.cpp:47:
    /ros-rolling-pcl-conversions-2.8.0-r1/include/pcl_conversions/pcl_conversions/pcl_conversions.h: In
      function 'void pcl_conversions::moveFromPCL(pcl::PCLImage&, sensor_msgs::msg::Image&)':
    /ros-rolling-pcl-conversions-2.8.0-r1/include/pcl_conversions/pcl_conversions/pcl_conversions.h:172:16:
      error: 'using sensor_msgs::msg::Image_<std::allocator<void> >::_data_type = class
      rosidl::Buffer<unsigned char, std::allocator<unsigned char> >' {aka 'class rosidl::Buffer<unsigned
      char, std::allocator<unsigned char> >'} has no member named 'swap'
      172 |     image.data.swap(pcl_image.data);
          |                ^~~~

These are caused by https://github.com/ros2/rosidl/pull/941 and
followup PRs, which change the type of `uint8[]` message fields from
`std::vector<uint8_t>` to `rosidl::Buffer<uint8_t>`. To maintain the
previous functionality, explicit typecasting is needed at a few
places. This causes invocation of the conversion operator [1], which
returns a reference to the underlying std::vector.

[1]: https://github.com/ros2/rosidl/blob/7c4e0f90f2979c16c906d65058fc7966360f52e1/rosidl_buffer/include/rosidl_buffer/buffer.hpp#L420

Signed-off-by: Michal Sojka <michal.sojka@cvut.cz>